name: Docker
on:
  push:
    paths:
      - .github/workflows/default.yml
      - .dockerignore
      - Dockerfile
  pull_request:
    paths:
      - .github/workflows/default.yml
      - .dockerignore
      - Dockerfile

jobs:
  verify:
    runs-on: self-hosted
    env:
      DOCKER_BUILDKIT: "1"
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build -f Dockerfile -t insight-it-web-iacdevops/poc-action-kube .

  publish:
    needs: [verify]
    if: github.event_name == 'push'
    runs-on: 
      labels: poc-onprem-self-builder-runner-deployment
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          driver: kubernetes 
          
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Set variables
        id: vars
        env:
          EVENT_NAME: ${{ github.event_name }}
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          TAG=${GITHUB_REF#refs/tags/}
          echo ::set-output name=commit::$(git rev-parse --short HEAD)
          echo ::set-output name=created::$(date -u +%Y-%m-%dT%H:%M:%SZ)
          if [ "$TAG" != "$GITHUB_REF" ]; then
            echo ::set-output name=version::$TAG
            echo ::set-output name=platforms::linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6,linux/s390x,linux/ppc64le
          elif [ "$BRANCH" = "master" ]; then
            echo ::set-output name=version::latest
            echo ::set-output name=platforms::linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6,linux/s390x,linux/ppc64le
          else
            echo ::set-output name=version::$BRANCH
            echo ::set-output name=platforms::linux/amd64
          fi

      - name: Build and push final image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          platforms: ${{ steps.vars.outputs.platforms }}
          build-args: |
            CREATED=${{ steps.vars.outputs.created }}
            COMMIT=${{ steps.vars.outputs.commit }}
            VERSION=${{ steps.vars.outputs.version }}
          tags: |
            ghcr.io/insight-it-web-iacdevops/poc-action-kube:${{ steps.vars.outputs.version }}
          push: true

